map = [
    "associate",
    "bind",
    "interact",
    "inhibit",
    "regulate",
    "transactivate",
    "activate",
    "acetylate",
    "phosphorylate",
    "suppress activity of",
    "act synergistically",
    "synergistic action",
    "deacetylate",
    "stimulate",
    "colocalize",
    "deaminate",
    "increase",
    "coimmunoprecipitate",
    "produce",
    "express",
    "hyperphosphorylate",
    "immunoprecipitate",
    "repress",
    "recruit",
    "synergize",
    "proteolyze",
    "synergistic interaction",
    "inactivate",
    "signal",
    "disassemble",
    "hydrolyse",
    "disrupt",
    "form",
    "iodinate",
    "prenylate",
    "degrade",
    "mannosylate",
    "suppress",
    "elevate",
    "coexpress",
    "dephosphorylate",
    "hyperacetylate",
    "ubiquitinate",
    "methylate",
    "block",
    "secrete",
    "release",
    "synergy",
    "hypermethylate",
    "synthesize",
    "coprecipitate",
    "demethylate",
    "mutate",
    "deactivate",
    "up-regulate",
    "overexpress",
    "translate",
    "depolymerize",
    "hypophosphorylate",
    "assemble",
    "work synergistically",
    "down-regulate",
    "copurify",
    "carbamylate",
    "diphosphorylate",
    "mediate a signal",
    "myristoylate",
    "dissociate from",
    "synergistic cooperation",
    "separate",
    "function synergistically",
    "bond",
    "sensitize",
    "synergistic association",
    "n-acetylate",
    "ubiquitinize",
    "polymerize",
    "homolog",
    "synergistic integration",
    "photoreactivate",
    "dissociate",
]


types_not_covered = [
    # "abrogate",
    # "instigate",
    # "liberate",
    # "attributable to",
    # "influence",
    # "required for",
    # "induce",
    # "break",
    # "lead to",
    # "cause",
    # "modify",
    # "link",
    # "depend on",
    # "may be responsible for",
    # "contain",
    # "tie",
    # "respond to",
    # "promote",
    # "sever",
    # "carry",
    # "react",
    # "constrain",
    # "antagonize",
    # "mediate",
    # "affect",
    # "alter",
    # "determine",
    # "conjugate",
    # "restrain",
    # "enhance",
    # "result in",
    # "due to",
    # "combine",
    # "accelerate",
    # "precede",
    # "form a complex",
    # "include",
    # "require",
    # "modulate",
    # "control",
    # "cleave",
    # "hinder",
    # "result from",
    # "incite",
    # "attach",
    # "as a result of",
    # "catalyze",
    # "add",
    # "connect",
    # "splice",
    # "attenuate",
    # "replace",
    # "hasten",
    # "attributed to",
    # "encode",
    # "generate",
    # "substitute",
    # "trigger",
    # "because of",
    # "couple",
    # "paralog",
    # "initiate",
    # "discharge",
    # "account for",
    # "limit",
    # "split",
    # "abolish",
    # "add up",
    # "pair",
    # "remove",
    # "digest",
    # "based on",
    # "prompt",
    # "further",
    # "have an active role in",
    # "aggregate",
    # "elicit",
    # "disengage",
    # "join",
    # "divide",
    # "analog",
    # "arrest",
    # "set free"
]

